"use client";

import { AlertTriangle, ArrowLeft, ArrowRight, CheckCircle2, CircleUserRound, Database, Pill, ShieldCheck, Stethoscope } from "lucide-react";
import { useMemo, useState } from "react";
import type { ApplicationConfig } from "./data";
import { applications } from "./data";
import { ArchitectureFlow, AuditTimeline, DemoVideoSection, Flow, HumanApprovalGate, LocalSectionNav, RiskControlPanel, Section, Shell, SystemStatusBadge, WorkflowExecutionPanel } from "./Shared";
import styles from "./Healthcare.module.css";
import MedicationVerificationPage from "./MedicationVerificationPage";

export default function HealthcareApplicationPage({ app }: { app:ApplicationConfig }) {
 if(app.slug==="medication-verification") return <MedicationVerificationPage/>;
 const nav=[{label:"Objective",href:"#objective"},{label:"Workflow",href:"#workflow"},{label:"Prototype",href:"#prototype"},{label:"Live Demo",href:"#live-demo"},{label:"Risks",href:"#risks"},{label:"Audit",href:"#audit"}];
 return <Shell><section className={styles.hero}><div className={styles.heroGrid}><div><a href="/projects/healthcare-workflow-intelligence" className={styles.micro}>← Healthcare Workflow Intelligence</a><div className={styles.eyebrow} style={{marginTop:30}}>Clinical workflow prototype / {app.risk} risk</div><h1 className={styles.h1}>{app.title}</h1><p className={styles.principle}>{app.statement}</p><p className={styles.lead} style={{marginTop:25}}>{app.description}</p><div className={styles.actions}><a href="#live-demo" className={`${styles.button} ${styles.primary}`}>Run synthetic demo <ArrowRight size={15}/></a><a href="#workflow" className={styles.button}>Inspect workflow</a></div><p className={styles.micro}>Concept prototype using fictional healthcare data. Not connected to a live clinical system and not intended for clinical use.</p></div><ArchitectureFlow nodes={app.workflow.map((s,i)=>({title:s,detail:i===app.workflow.length-2?"Authorised human decision point":"Controlled workflow state",checkpoint:i===1||i===app.workflow.length-2}))}/></div></section><LocalSectionNav items={nav}/>
 <Section id="objective" eyebrow="Objective and scenario" title={app.objective} intro={app.scenario}><div className={styles.grid2}><div className={styles.card}><AlertTriangle className={styles.icon}/><h3>Current pain point</h3><p>{app.problem}</p></div><div className={styles.card}><CheckCircle2 className={styles.icon}/><h3>Proposed solution</h3><p>{app.description} The workflow exposes exceptions and retains explicit human authority.</p></div></div></Section>
 <Section id="roles" eyebrow="Division of responsibility" title="Intelligence inside operational boundaries" intro="The agent handles bounded language tasks. n8n maintains workflow state, rules, permissions and traceability."><div className={styles.grid2}><div className={styles.card}><CircleUserRound className={styles.icon}/><h3>Role of the AI agent</h3>{app.ai.map(x=><p style={{marginTop:10}} key={x}>• {x}</p>)}<p style={{marginTop:20,color:"#ffb5a6"}}>AI must not make the clinical decision.</p></div><div className={styles.card}><Database className={styles.icon}/><h3>Role of n8n</h3>{app.n8n.map(x=><p style={{marginTop:10}} key={x}>• {x}</p>)}<p style={{marginTop:20}}>Actions use approved interfaces and versioned workflow logic.</p></div></div></Section>
 <Section id="workflow" eyebrow="Detailed n8n workflow" title="A visible path from event to resolution" intro="Every transition has a defined trigger, owner, timeout and auditable outcome."><Flow steps={app.workflow}/><div style={{marginTop:24}}><RiskControlPanel application={app}/></div></Section>
 <Section id="prototype" eyebrow="Product prototype" title="Designed around exception handling" intro="The interface separates system events, workflow execution, human approval and final clinical status."><ApplicationPrototype app={app}/></Section>
 <Section id="users" eyebrow="User roles" title="One case, role-specific views" intro="Each role sees the minimum information and actions needed for its responsibility."><RoleSwitcher roles={app.roles} app={app}/></Section>
 <Section id="video" eyebrow="Video demonstration" title="Scenario Demo — From Trigger to Clinical Resolution"><DemoVideoSection title={`${app.title} scenario demo`}/></Section>
 <Section id="live-demo" eyebrow="Interactive concept" title="Run the workflow with synthetic local data" intro="Change the scenario, start a deterministic run and complete the human approval gate."><div className={styles.disclaimer}>Concept prototype using fictional healthcare data. Not connected to a live clinical system and not intended for clinical use.</div><div className={styles.demoGrid} style={{marginTop:16}}><LiveDemo app={app}/><WorkflowExecutionPanel labels={app.workflow} waitingAt={app.workflow.length-2}/></div></Section>
 <div id="risks"><Section eyebrow="Workflow assurance" title="Risk is part of the design, not a footnote" intro="Controls address false positives, false negatives, stale context, wrong recipients, duplication, integration failure, automation bias and unavailable systems." wide><RiskControlPanel application={app}/><div className={styles.grid2} style={{marginTop:16}}><HumanApprovalGate>{app.slug==="medication-verification"?"A nurse reviews the comparison; a doctor or pharmacist clarifies when required. The interface never declares medication approved.":app.slug==="discharge-intelligence"?"Operational task completion cannot authorise discharge. The responsible clinician confirms clinical fitness.":"Acknowledgement does not mean clinical review or treatment. Those states remain separate and visible."}</HumanApprovalGate><div className={styles.card}><ShieldCheck color="#7ce2ca"/><h3>Downtime and fallback</h3><p>Stop new automation, surface the last-known timestamp, reconcile queued events and use the approved manual communication pathway. Never silently assume completion.</p></div></div></Section></div>
 <Section id="audit" eyebrow="Audit and monitoring" title="Trace the workflow, not only the final state" intro="The record contains trigger, source versions, rule and workflow versions, recipients, decisions, escalation and completion."><div className={styles.grid2}><AuditTimeline items={["Event received","Identity and encounter validated","Workflow v1.0 executed","Human gate opened","Decision recorded","Outcome reconciled"]}/><div className={styles.card}><h3>Operational monitoring</h3><div className={styles.grid2} style={{marginTop:15}}>{[["Data freshness","Live in simulation"],["Workflow version","HWI-1.0"],["Integration mode","Mock adapter"],["Fallback","Manual pathway ready"]].map(([a,b])=><div className={styles.card} key={a}><p>{a}</p><strong>{b}</strong></div>)}</div></div></div></Section>
 <Section id="further" eyebrow="Further applications" title="Continue through the healthcare workflow system"><div className={styles.grid3}>{Object.values(applications).filter(x=>x.slug!==app.slug).map(x=><a className={styles.card} key={x.slug} href={`/projects/healthcare-workflow-intelligence/${x.slug}`}><SystemStatusBadge label={`${x.risk} risk`}/><h3>{x.title}</h3><p>{x.statement}</p><div className={styles.actions}>Explore application <ArrowRight size={15}/></div></a>)}<a className={styles.card} href="/projects/healthcare-workflow-intelligence"><ArrowLeft className={styles.icon}/><h3>Healthcare Workflow Intelligence</h3><p>Return to the strategy, architecture, governance model and application landscape.</p></a></div></Section>
 </Shell>
}

function RoleSwitcher({roles,app}:{roles:string[];app:ApplicationConfig}){const [role,setRole]=useState(roles[0]);return <div className={styles.card}><div className={styles.tabs} role="tablist" aria-label="Prototype user role">{roles.map(r=><button role="tab" aria-selected={role===r} className={`${styles.tab} ${role===r?styles.tabActive:""}`} onClick={()=>setRole(r)} key={r}>{r}</button>)}</div><div className={styles.card}><Stethoscope className={styles.icon}/><h3>{role} view</h3><p>{role} sees assigned work, elapsed time, source freshness and the actions permitted for this role in the {app.title.toLowerCase()} workflow.</p></div></div>}

function ApplicationPrototype({app}:{app:ApplicationConfig}){if(app.slug==="medication-verification")return <MedicationPrototype/>;if(app.slug==="discharge-intelligence")return <DischargePrototype/>;return <CriticalPrototype/>}

function MedicationPrototype(){const meds=[["Metformin","500 mg BD","500 mg BD","Matched"],["Amlodipine","10 mg daily","5 mg daily","Dose discrepancy"],["Atorvastatin","20 mg nocte","—","Missing order"]];return <div className={styles.prototype}><div className={styles.prototypeBar}><span>Fictional patient · HN-204810-7</span><SystemStatusBadge label="Data fresh · 12 sec"/></div><div className={styles.prototypeBody}><div className={styles.metricGrid}>{[["4","Matched"],["2","Discrepancies"],["2","Unresolved"]].map(([a,b])=><div className={styles.metric} key={b}><b>{a}</b><span>{b}</span></div>)}</div><div style={{overflowX:"auto",marginTop:15}}><div className={styles.matrix}>{meds.map((r,i)=><div className={styles.matrixRow} style={{gridTemplateColumns:"1.1fr 1fr 1fr 1fr"}} key={r[0]}>{r.map((x,j)=><div key={x} style={j===3&&i>0?{color:"#ffab92"}:{}}>{x}</div>)}</div>)}</div></div><p className={styles.disclaimer} style={{marginTop:15}}>Comparison completed. Clinical verification remains required.</p></div></div>}
function DischargePrototype(){return <div className={styles.prototype}><div className={styles.prototypeBar}><span>Ward 7A · Discharge command centre</span><SystemStatusBadge label="Updated 12 sec ago"/></div><div className={styles.prototypeBody}><div className={styles.grid3}>{[["PX-142","82%","Pharmacy reconciliation","38 min"],["PX-155","64%","Patient education","24 min"],["PX-161","94%","Clinician confirmation","8 min"]].map(([id,p,b,t])=><div className={styles.card} key={id}><SystemStatusBadge label={`${p} ready`}/><h3>{id}</h3><p>Blocking: {b}</p><p style={{marginTop:8}}>Waiting {t}</p></div>)}</div><p className={styles.disclaimer} style={{marginTop:15}}>Operational readiness is not clinical fitness for discharge. Final confirmation remains with the responsible clinician.</p></div></div>}
function CriticalPrototype(){return <div className={styles.prototype}><div className={styles.prototypeBar}><span>Critical result communication board</span><SystemStatusBadge label="Simulation active"/></div><div className={styles.prototypeBody}><div className={styles.grid2}>{[["Awaiting acknowledgement","PX-882 · K+ 6.7 mmol/L","01:42"],["Escalated","PX-731 · Hb 5.8 g/dL","Stage 2"],["Completed","PX-540 · Glucose 2.1 mmol/L","Clinically reviewed"]].map(([s,r,t])=><div className={styles.card} key={r}><SystemStatusBadge label={s} tone={s==="Escalated"?"warn":"ok"}/><h3>{r}</h3><p>Medical team · Ward 5B</p><p style={{marginTop:8}}>{t}</p></div>)}</div><div className={styles.chips} style={{marginTop:15}}>{["Delivered","Acknowledged","Clinically reviewed","Action documented"].map(x=><span className={styles.chip} key={x}>{x}</span>)}</div></div></div>}

function LiveDemo({app}:{app:ApplicationConfig}){const [choice,setChoice]=useState(app.slug==="medication-verification"?"Change dose":app.slug==="discharge-intelligence"?"Delay pharmacy":"First clinician does not respond");const choices=useMemo(()=>app.slug==="medication-verification"?["Change dose","Remove medication","Alter frequency"]:app.slug==="discharge-intelligence"?["Delay pharmacy","Delay education","Complete all tasks"]:["First clinician responds","First clinician does not respond","Patient transfers ward"],[app.slug]);return <div className={styles.card}><div className={styles.eyebrow}>Simulated hospital event</div><h3>Scenario controls</h3><p>Select an event, then run the workflow in the execution panel.</p><div className={styles.tabs} style={{marginTop:18}}>{choices.map(c=><button onClick={()=>setChoice(c)} className={`${styles.tab} ${choice===c?styles.tabActive:""}`} key={c}>{c}</button>)}</div><div className={styles.card}><Pill className={styles.icon}/><h3>{choice}</h3><p>{app.slug==="medication-verification"?"A synthetic order version now differs from its fictional documentation source.":app.slug==="discharge-intelligence"?"The assigned task crosses its demonstration reminder threshold.":"The secure alert timer progresses against a fictional escalation policy."}</p></div><p className={styles.micro}>Inputs are constrained to synthetic scenario values. Reset or replay from the workflow panel.</p></div>}
