export type MedicationCatalogueItem = {
  id: string;
  name: string;
  alias?: string;
  forms: string[];
  routes: string[];
  doses: string[];
  frequencies: string[];
  prnObserved: boolean;
  carrier?: string;
  instructions?: string;
  risk: boolean;
  sourcePatients: string[];
};

const rows: Omit<MedicationCatalogueItem, "id">[] = [
  {
    name: "2D:1S",
    forms: ["Intravenous fluid"],
    routes: ["IV", "Continuous IV infusion"],
    doses: [],
    frequencies: ["Q6H"],
    prnObserved: false,
    carrier: "500 mL",
    instructions: "If increase in abdominal pain / PVB",
    risk: false,
    sourcePatients: ["Patient 3", "Patient 4"],
  },
  {
    name: "Amoxycillin (Sodium) + Clavulanic Acid",
    alias: "Augmentin",
    forms: ["Injection"],
    routes: ["IV", "IV bolus"],
    doses: ["1200 mg"],
    frequencies: ["On induction", "Every 3 hours PRN", "One dose"],
    prnObserved: true,
    instructions: "Prophylactic; up to 3 doses in 24 hours",
    risk: true,
    sourcePatients: ["Patient 12", "Patient 4", "Patient 9"],
  },
  {
    name: "Amoxycillin (Trihydrate) + Clavulanic Acid",
    alias: "Augmentin",
    forms: ["Tablet"],
    routes: ["ORAL", "Oral administration"],
    doses: ["1000 mg"],
    frequencies: ["BD"],
    prnObserved: false,
    instructions: "Course duration/date fields visible but ambiguous",
    risk: false,
    sourcePatients: ["Patient 7"],
  },
  {
    name: "Apixaban",
    forms: ["Tablet"],
    routes: ["ORAL", "Oral administration"],
    doses: ["5 mg"],
    frequencies: ["BD"],
    prnObserved: false,
    instructions: "SFI",
    risk: true,
    sourcePatients: ["Patient 10"],
  },
  {
    name: "Atorvastatin",
    alias: "Lipitor",
    forms: ["Tablet"],
    routes: ["ORAL", "Oral administration"],
    doses: ["5 mg"],
    frequencies: ["NOCTE"],
    prnObserved: false,
    instructions: "Reduce dosage",
    risk: false,
    sourcePatients: ["Patient 7"],
  },
  {
    name: "Ceftriaxone Disodium",
    alias: "Rocephin",
    forms: ["Injection"],
    routes: ["IV", "IV bolus"],
    doses: ["1 g"],
    frequencies: ["Q12H"],
    prnObserved: false,
    risk: false,
    sourcePatients: ["Patient 1"],
  },
  {
    name: "Cefuroxime Sodium",
    alias: "Zinacef",
    forms: ["Injection"],
    routes: ["IV", "IV bolus"],
    doses: ["750 mg"],
    frequencies: ["On induction", "One dose"],
    prnObserved: false,
    instructions: "Prophylactic",
    risk: true,
    sourcePatients: ["Patient 5"],
  },
  {
    name: "Chlorhexidine Gluconate",
    forms: ["Mouthwash"],
    routes: ["ORAL_CAVITY", "Mouthwash"],
    doses: ["10 mL"],
    frequencies: ["BD"],
    prnObserved: false,
    instructions: "0.2%; for 1 week",
    risk: false,
    sourcePatients: ["Patient 4"],
  },
  {
    name: "Chlorpheniramine Maleate",
    alias: "Piriton",
    forms: ["Injection"],
    routes: ["IV", "IV bolus"],
    doses: ["10 mg"],
    frequencies: ["Q8H"],
    prnObserved: true,
    risk: false,
    sourcePatients: ["Patient 1"],
  },
  {
    name: "Cholecalciferol",
    alias: "Vitamin D3",
    forms: ["Tablet"],
    routes: ["ORAL", "Oral administration"],
    doses: ["1000 IU"],
    frequencies: ["DAILY"],
    prnObserved: false,
    risk: false,
    sourcePatients: ["Patient 5"],
  },
  {
    name: "Cinacalcet HCl",
    forms: ["Tablet"],
    routes: ["ORAL", "Oral administration"],
    doses: ["30 mg"],
    frequencies: ["DAILY"],
    prnObserved: false,
    risk: true,
    sourcePatients: ["Patient 5"],
  },
  {
    name: "Clonazepam",
    forms: ["Tablet"],
    routes: ["ORAL", "Oral administration"],
    doses: ["1 mg"],
    frequencies: ["NOCTE PRN"],
    prnObserved: true,
    instructions: "Night dose as required",
    risk: false,
    sourcePatients: ["Patient 2"],
  },
  {
    name: "Dapagliflozin Propanediol",
    forms: ["Tablet"],
    routes: ["ORAL", "Oral administration"],
    doses: ["10 mg"],
    frequencies: ["DAILY"],
    prnObserved: false,
    risk: true,
    sourcePatients: ["Patient 10"],
  },
  {
    name: "Digoxin",
    forms: ["Tablet"],
    routes: ["ORAL", "Oral administration"],
    doses: ["62.5 microgram"],
    frequencies: ["DAILY"],
    prnObserved: false,
    risk: false,
    sourcePatients: ["Patient 10"],
  },
  {
    name: "Diltiazem HCl",
    forms: ["Controlled-release tablet"],
    routes: ["ORAL", "Oral administration"],
    doses: ["60 mg"],
    frequencies: ["TDS"],
    prnObserved: false,
    instructions: "Withhold if HR < 60",
    risk: false,
    sourcePatients: ["Patient 10"],
  },
  {
    name: "Entecavir",
    forms: ["Tablet"],
    routes: ["ORAL", "Oral administration"],
    doses: ["0.5 mg"],
    frequencies: ["DAILY"],
    prnObserved: false,
    risk: true,
    sourcePatients: ["Patient 5"],
  },
  {
    name: "Famotidine",
    alias: "Pepcidine",
    forms: ["Tablet"],
    routes: ["ORAL", "Oral administration"],
    doses: ["20 mg"],
    frequencies: ["BD"],
    prnObserved: true,
    risk: false,
    sourcePatients: ["Patient 11"],
  },
  {
    name: "Ferrous Sulphate",
    alias: "FeSO4",
    forms: ["Tablet"],
    routes: ["ORAL", "Oral administration"],
    doses: ["300 mg"],
    frequencies: ["DAILY"],
    prnObserved: false,
    risk: false,
    sourcePatients: ["Patient 9"],
  },
  {
    name: "Folic Acid",
    forms: ["Tablet"],
    routes: ["ORAL", "Oral administration"],
    doses: ["5 mg"],
    frequencies: ["DAILY"],
    prnObserved: false,
    risk: false,
    sourcePatients: ["Patient 10"],
  },
  {
    name: "Gliclazide",
    alias: "Diamicron",
    forms: ["Tablet"],
    routes: ["ORAL", "Oral administration"],
    doses: ["40 mg", "80 mg"],
    frequencies: ["BD", "OM"],
    prnObserved: false,
    risk: false,
    sourcePatients: ["Patient 8", "Patient 9"],
  },
  {
    name: "Granisetron",
    forms: ["Injection"],
    routes: ["IV", "IV bolus"],
    doses: ["1 mg"],
    frequencies: ["Q24H"],
    prnObserved: true,
    risk: true,
    sourcePatients: ["Patient 1"],
  },
  {
    name: "Lactulose",
    forms: ["Liquid"],
    routes: ["ORAL", "Oral administration"],
    doses: ["10 mL"],
    frequencies: ["BD"],
    prnObserved: false,
    risk: false,
    sourcePatients: ["Patient 8"],
  },
  {
    name: "Losartan Potassium",
    forms: ["Tablet"],
    routes: ["ORAL", "Oral administration"],
    doses: ["75 mg"],
    frequencies: ["DAILY"],
    prnObserved: false,
    risk: false,
    sourcePatients: ["Patient 8"],
  },
  {
    name: "Metformin HCl",
    alias: "Glucophage XR",
    forms: ["Prolonged-release tablet", "Tablet"],
    routes: ["ORAL", "Oral administration"],
    doses: ["1000 mg"],
    frequencies: ["BD"],
    prnObserved: false,
    risk: true,
    sourcePatients: ["Patient 8", "Patient 9"],
  },
  {
    name: "Metoclopramide HCl",
    alias: "Maxolon",
    forms: ["Injection"],
    routes: ["IV", "IV bolus"],
    doses: ["10 mg"],
    frequencies: ["Q6H", "Q8H"],
    prnObserved: true,
    risk: false,
    sourcePatients: ["Patient 1", "Patient 4"],
  },
  {
    name: "Metoprolol Tartrate",
    alias: "Betaloc",
    forms: ["Tablet"],
    routes: ["ORAL", "Oral administration"],
    doses: ["50 mg"],
    frequencies: ["BD"],
    prnObserved: false,
    risk: false,
    sourcePatients: ["Patient 10"],
  },
  {
    name: "Metronidazole",
    alias: "Flagyl",
    forms: ["Infusion"],
    routes: ["IV", "Intermittent IV infusion"],
    doses: ["500 mg"],
    frequencies: ["On induction", "One dose"],
    prnObserved: false,
    carrier: "0.5% infusion",
    instructions: "Over 30 minutes; prophylactic",
    risk: true,
    sourcePatients: ["Patient 5"],
  },
  {
    name: "Mirabegron",
    forms: ["Prolonged-release tablet"],
    routes: ["ORAL", "Oral administration"],
    doses: ["50 mg"],
    frequencies: ["DAILY"],
    prnObserved: false,
    risk: true,
    sourcePatients: ["Patient 7"],
  },
  {
    name: "Misoprostol",
    alias: "Cytotec",
    forms: ["Tablet"],
    routes: ["ORAL", "Oral administration"],
    doses: ["200 microgram"],
    frequencies: ["NOCTE", "One dose"],
    prnObserved: false,
    risk: false,
    sourcePatients: ["Patient 12"],
  },
  {
    name: "Norethisterone",
    alias: "Primolut N",
    forms: ["Tablet"],
    routes: ["ORAL", "Oral administration"],
    doses: ["5 mg"],
    frequencies: ["TDS"],
    prnObserved: false,
    instructions: "Day 1 to day 21 of treatment cycle",
    risk: false,
    sourcePatients: ["Patient 11"],
  },
  {
    name: "Oxytocin",
    alias: "Syntocinon",
    forms: ["Injection"],
    routes: ["IV", "Intermittent IV infusion"],
    doses: ["40 units"],
    frequencies: ["Q4H"],
    prnObserved: false,
    carrier: "Sodium Chloride 0.9% · 500 mL · 4 hours",
    instructions: "Till reassessment",
    risk: true,
    sourcePatients: ["Patient 3"],
  },
  {
    name: "Pantoprazole Sodium",
    alias: "Pantoloc",
    forms: ["Injection"],
    routes: ["IV", "IV bolus"],
    doses: ["40 mg"],
    frequencies: ["Q24H"],
    prnObserved: false,
    risk: true,
    sourcePatients: ["Patient 1"],
  },
  {
    name: "Pantoprazole Sodium Sesquihydrate",
    alias: "Pantoloc",
    forms: ["Tablet"],
    routes: ["ORAL", "Oral administration"],
    doses: ["40 mg"],
    frequencies: ["DAILY"],
    prnObserved: false,
    risk: false,
    sourcePatients: ["Patient 10"],
  },
  {
    name: "Paracetamol",
    alias: "Panadol",
    forms: ["Tablet"],
    routes: ["ORAL", "Oral administration"],
    doses: ["500 mg", "1000 mg"],
    frequencies: ["Q4H", "Q6H", "QID", "On call to operating theatre"],
    prnObserved: true,
    instructions: "Maximum 4 g/day; withhold if given within 6 hours",
    risk: false,
    sourcePatients: [
      "Patient 11",
      "Patient 2",
      "Patient 3",
      "Patient 4",
      "Patient 5",
      "Patient 7",
    ],
  },
  {
    name: "Pethidine HCl",
    forms: ["Injection"],
    routes: ["IM", "Intramuscular injection"],
    doses: ["50 mg"],
    frequencies: ["Q6H"],
    prnObserved: true,
    risk: true,
    sourcePatients: ["Patient 3"],
  },
  {
    name: "Potassium Chloride",
    alias: "Slow K",
    forms: ["Sustained-release tablet"],
    routes: ["ORAL", "Oral administration"],
    doses: ["600 mg"],
    frequencies: ["DAILY"],
    prnObserved: false,
    risk: false,
    sourcePatients: ["Patient 8"],
  },
  {
    name: "Pregabalin",
    alias: "Lyrica",
    forms: ["Capsule"],
    routes: ["ORAL", "Oral administration"],
    doses: ["25 mg"],
    frequencies: ["NOCTE"],
    prnObserved: false,
    instructions: "Night dose",
    risk: false,
    sourcePatients: ["Patient 2"],
  },
  {
    name: "Pyridoxine HCl",
    alias: "Vitamin B6",
    forms: ["Tablet"],
    routes: ["ORAL", "Oral administration"],
    doses: ["50 mg"],
    frequencies: ["NOCTE"],
    prnObserved: false,
    risk: false,
    sourcePatients: ["Patient 7"],
  },
  {
    name: "Senna",
    forms: ["Tablet"],
    routes: ["ORAL", "Oral administration"],
    doses: ["7.5 mg"],
    frequencies: ["PM"],
    prnObserved: false,
    risk: false,
    sourcePatients: ["Patient 8"],
  },
  {
    name: "Sertraline HCl",
    forms: ["Tablet"],
    routes: ["ORAL", "Oral administration"],
    doses: ["100 mg"],
    frequencies: ["DAILY"],
    prnObserved: false,
    instructions: "Medication note: collected 10 tablets from patient",
    risk: false,
    sourcePatients: ["Patient 2", "Patient 6"],
  },
  {
    name: "Sodium Citrate",
    forms: ["Powder"],
    routes: ["ORAL", "Oral administration"],
    doses: ["2.7 g"],
    frequencies: ["On call to operating theatre"],
    prnObserved: false,
    carrier: "30 mL",
    instructions: "30 mL",
    risk: false,
    sourcePatients: ["Patient 9"],
  },
  {
    name: "Thyroxine Sodium",
    forms: ["Tablet"],
    routes: ["ORAL", "Oral administration"],
    doses: ["50 microgram", "100 microgram"],
    frequencies: ["Variable weekday schedule"],
    prnObserved: false,
    instructions: "50 micrograms Sunday; 100 micrograms Monday–Saturday",
    risk: false,
    sourcePatients: ["Patient 12"],
  },
  {
    name: "Tranexamic Acid",
    alias: "Transamin",
    forms: ["Capsule"],
    routes: ["ORAL", "Oral administration"],
    doses: ["500 mg"],
    frequencies: ["QID"],
    prnObserved: true,
    risk: false,
    sourcePatients: ["Patient 11"],
  },
];

export const medicationCatalogue: MedicationCatalogueItem[] = rows.map(
  (row, index) => ({ ...row, id: `MED-${String(index + 1).padStart(4, "0")}` }),
);
export const medicationCatalogueByName = new Map(
  medicationCatalogue.map((item) => [item.name, item]),
);
