"use client";
import {AlertTriangle,CheckCircle2,ChevronRight,Clock3,Search,ShieldAlert,UserRound} from "lucide-react";
import {lazy,Suspense,useMemo,useState} from "react";
import {caseCounts,demoCases} from "./medication-cases";
import type {FieldComparison} from "./medication-engine";
import styles from "./MedicationVerification.module.css";
import RealWorldIntegration from "./RealWorldIntegration";
const Icon=({state}:{state:string})=>state==="MATCH"?<CheckCircle2/>:state==="REVIEW"?<Clock3/>:<AlertTriangle/>;
const workflow=["Record received","Identity validation","Version validation","Deterministic comparison","Case classification","Reviewer assignment","Notification","Wait","Escalation if overdue","Re-run after source update","Audit closure"];
const MedicationProductStory3D=lazy(()=>import("./MedicationProductStory3D"));
export default function MedicationVerificationPage(){const [query,setQuery]=useState(""),[result,setResult]=useState("ALL"),[selected,setSelected]=useState(demoCases[10]),[field,setField]=useState<FieldComparison>(demoCases[10].comparison.fields[0]),[mobileApp,setMobileApp]=useState<"EDOC"|"IPMOE">("EDOC"),[comment,setComment]=useState("");const cases=useMemo(()=>demoCases.filter(c=>(result==="ALL"||c.comparison.overallResult===result)&&`${c.id} ${c.title}`.toLowerCase().includes(query.toLowerCase())),[query,result]);const choose=(c:typeof selected)=>{setSelected(c);setField(c.comparison.fields.find(x=>x.result!=="MATCH")||c.comparison.fields[0])};return <main className={styles.root}>
 <aside className={styles.notice} role="note"><ShieldAlert/> <span><b>Demonstration only.</b> Synthetic data and generic prototype rules are used. This product is not connected to CMS, e-Documentation, IPMOE or any live clinical system.</span></aside>
 <header className={styles.hero}><div><p className={styles.eyebrow}>Wing Yee AI Lab · Clinical workflow prototype</p><h1>Medication<br/>Consistency Verification</h1><p>A read-only layer that compares medication records and routes exceptions for authorised human review.</p><strong>The system checks consistency. Healthcare professionals determine correctness.</strong><div className={styles.productActions}><a href="/projects/healthcare-workflow-intelligence/medication-verification/demo">Launch Staff Demo</a><a href="#product-story">View Integration Architecture</a></div></div><div className={styles.heroPreview}><span>e-Documentation</span><b>Read-only comparison</b><span>IPMOE</span></div></header>
 <Suspense fallback={<div className={styles.storyLoading} role="status">Loading interactive product story…</div>}><MedicationProductStory3D/></Suspense>
 <RealWorldIntegration/>
 <section className={styles.workspace} aria-labelledby="workspace-title"><div className={styles.sectionHead}><div><p className={styles.eyebrow}>Clinical workspace</p><h2 id="workspace-title">Review the difference, not two complete records.</h2></div><p>30 deterministic synthetic cases. Prototype rules pending approved clinical standards.</p></div>
 <div className={styles.metrics}>{[[30,"Total cases"],[caseCounts.MATCH,"Match"],[caseCounts.REVIEW,"Review required"],[caseCounts.MISMATCH,"Mismatch"]].map(([n,l])=><article key={String(l)}><b>{n}</b><span>{l}</span></article>)}</div>
 <div className={styles.controls}><label><Search/><span className={styles.sr}>Search cases</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search case or medication"/></label><div role="group" aria-label="Filter by result">{["ALL","MATCH","REVIEW","MISMATCH"].map(x=><button aria-pressed={result===x} onClick={()=>setResult(x)} key={x}>{x}</button>)}</div></div>
 <div className={styles.clinicalGrid}><nav className={styles.caseList} aria-label="Synthetic cases">{cases.map(c=><button className={selected.id===c.id?styles.selected:""} onClick={()=>choose(c)} key={c.id}><Icon state={c.comparison.overallResult}/><span><b>{c.id} · {c.title}</b><small>{c.kind} · {c.workflowStatus}</small></span><em data-state={c.comparison.overallResult}>{c.comparison.overallResult}</em><ChevronRight/></button>)}</nav>
 <div className={styles.caseDetail}><div className={styles.caseTitle}><div><p className={styles.eyebrow}>{selected.id} · Synthetic record</p><h3>{selected.title}</h3></div><span data-state={selected.comparison.overallResult}><Icon state={selected.comparison.overallResult}/>{selected.comparison.overallResult}</span></div>
 <div className={styles.mobileTabs}>{[["EDOC","e-Documentation"],["IPMOE","IPMOE"]].map(([v,l])=><button aria-pressed={mobileApp===v} onClick={()=>setMobileApp(v as typeof mobileApp)} key={v}>{l}</button>)}</div><div className={styles.apps}><SourceCard title="e-Documentation" record={selected.eDocumentation} hidden={mobileApp!=="EDOC"}/><SourceCard title="IPMOE" record={selected.ipmoe} hidden={mobileApp!=="IPMOE"}/></div>
 <div className={styles.result}><Icon state={selected.comparison.overallResult}/><div><b>{selected.comparison.message}</b><p>Consistency does not establish clinical appropriateness. Required professional verification remains applicable.</p></div></div>
 <div className={styles.inspector}><div className={styles.fieldList}>{selected.comparison.fields.map(f=><button aria-pressed={field.field===f.field} onClick={()=>setField(f)} key={f.field}><Icon state={f.result}/><span>{f.field}</span><small>{f.result}</small></button>)}</div><article className={styles.rule}><p className={styles.eyebrow}>Comparison inspector</p><h4>{field.field}</h4><dl><div><dt>e-Documentation</dt><dd>{String(field.eDocumentationValue??"Not supplied")}</dd></div><div><dt>IPMOE</dt><dd>{String(field.ipmoeValue??"Not supplied")}</dd></div><div><dt>Normalised</dt><dd>{String(field.normalisedEDocumentation??"—")} / {String(field.normalisedIpmoe??"—")}</dd></div><div><dt>Prototype rule</dt><dd>{field.ruleId} · v{field.ruleVersion}</dd></div><div><dt>Reason</dt><dd>{field.reasonCode}</dd></div></dl><p>{field.explanation}</p><strong>{field.action}</strong></article></div>
 <ReviewPanel comment={comment} setComment={setComment}/></div></div></section>
 <section className={styles.orchestration}><p className={styles.eyebrow}>Mock n8n orchestration</p><h2>Coordinates workflow. Never determines clinical correctness.</h2><div className={styles.rail}>{workflow.map((x,i)=><div key={x}><span>{String(i+1).padStart(2,"0")}</span><b>{x}</b></div>)}</div><label>Generic demonstration escalation timer <select defaultValue="30"><option value="15">15 minutes</option><option value="30">30 minutes</option><option value="60">60 minutes</option></select></label></section>
 <section className={styles.audit}><p className={styles.eyebrow}>Prototype audit trail</p><h2>Every comparison remains inspectable.</h2><div>{[["Source records",`${selected.eDocumentation.sourceRecordId} / ${selected.ipmoe.sourceRecordId}`],["Source versions",`${selected.eDocumentation.version} / ${selected.ipmoe.version}`],["Engine",selected.comparison.engineVersion],["Rule set",selected.comparison.fields.map(f=>`${f.ruleId} v${f.ruleVersion}`).filter((v,i,a)=>a.indexOf(v)===i).join(" · ")],["Result history",`Received → ${selected.comparison.overallResult}`],["Reviewer actions","No clinical decision recorded"],["Re-run history","Initial deterministic run"],["Closure reason",selected.workflowStatus==="Closed"?"No configured discrepancy detected":"Open"]].map(([a,b])=><article key={a}><span>{a}</span><b>{b}</b></article>)}</div><p>This is a prototype audit trail; no claim of legal immutability is made.</p></section>
 </main>}
function SourceCard({title,record,hidden}:{title:string;record:any;hidden:boolean}){return <article className={`${styles.source} ${hidden?styles.mobileHidden:""}`}><header><span>Mock application</span><b>{title}</b><small>{record.sourceRecordId} · v{record.version}</small></header><dl>{[["Patient",record.patientId],["Medication",record.medicationName],["Dose",record.doseValue==null?"Not supplied":`${record.doseValue} ${record.doseUnit}`],["Route",record.route||"Not supplied"],["Timing",record.scheduledTime||record.intervalMinutes&&`${record.intervalMinutes} minutes`||"Not supplied"],["Status",record.orderStatus],...(record.isIntravenousFluid?[["Fluid",record.fluidName],["Volume",`${record.fluidVolumeMl} mL`],["Duration",record.infusionDurationMinutes?`${record.infusionDurationMinutes} minutes`:record.infusionRateMlHour?`${record.infusionRateMlHour} mL/hour`:"Not supplied"]]:[])].map(([a,b])=><div key={a}><dt>{a}</dt><dd>{b}</dd></div>)}</dl></article>}
function ReviewPanel({comment,setComment}:{comment:string;setComment:(x:string)=>void}){return <aside className={styles.review}><p className={styles.eyebrow}>Human review</p><h4><UserRound/> Authorised workflow actions</h4><div>{["Acknowledge case","Request clarification","Documentation requires correction","IPMOE requires correction","Unable to determine","Reassign","Re-run verification"].map(x=><button key={x}>{x}</button>)}</div><label>Add comment<textarea value={comment} onChange={e=>setComment(e.target.value)} placeholder="Synthetic workflow note"/></label><button className={styles.save}>Add comment</button><small>Actions record workflow state only. Corrections occur in the relevant source application.</small></aside>}
