"use client";
import {Canvas,useFrame} from "@react-three/fiber";
import {Environment,Float,MeshTransmissionMaterial} from "@react-three/drei";
import gsap from "gsap";
import {ScrollTrigger} from "gsap/ScrollTrigger";
import {useEffect,useRef,useState} from "react";
import type * as React from "react";
import type {Group} from "three";
import styles from "./MedicationVerification.module.css";
function Tablet({side}:{side:-1|1}){return <group position={[side*3.1,.75,0]} rotation={[0,side*-.2,0]}><mesh><boxGeometry args={[2.25,3.2,.18]}/><MeshTransmissionMaterial transmission={.92} thickness={.55} roughness={.18} chromaticAberration={.025} color={side<0?"#dfe9ff":"#e9e2ff"}/></mesh>{[-.72,-.24,.24,.72].map((y,i)=><mesh key={y} position={[0,y,.13]}><boxGeometry args={[i===0?1.45:1.7,.11,.035]}/><meshStandardMaterial color={i===2?"#8b7bff":"#91a4b4"}/></mesh>)}</group>}
function Token({index}:{index:number}){const ref=useRef<Group>(null);useFrame(({clock})=>{if(ref.current)ref.current.position.y=.9+index*.28+Math.sin(clock.elapsedTime*1.2+index)*.05});return <group ref={ref} position={[-1.55,.9+index*.28,.25]}><mesh><capsuleGeometry args={[.08,.55,4,8]}/><meshStandardMaterial color={index===3?"#ed9b72":index===2?"#d4a84d":"#7668df"}/></mesh></group>}
function Scene({progress}:{progress:React.MutableRefObject<number>}){const root=useRef<Group>(null);useFrame(()=>{if(root.current){root.current.rotation.y=(progress.current-.5)*.16;root.current.position.y=Math.sin(progress.current*Math.PI)*.15}});return <><ambientLight intensity={1.35}/><directionalLight position={[4,6,5]} intensity={3}/><group ref={root}><Tablet side={-1}/><Tablet side={1}/><Float speed={1.4} rotationIntensity={.14} floatIntensity={.25}><mesh position={[0,.75,.15]}><icosahedronGeometry args={[1.05,2]}/><MeshTransmissionMaterial transmission={.75} thickness={1.8} roughness={.12} color="#7465d8"/></mesh></Float>{[0,1,2,3,4].map(i=><Token key={i} index={i}/>)}<mesh position={[0,-1.7,0]}><boxGeometry args={[6.8,.12,.2]}/><meshStandardMaterial color="#7e73d4"/></mesh><mesh position={[3,-1.7,.12]}><sphereGeometry args={[.32,24,24]}/><meshStandardMaterial color="#4a9c89"/></mesh></group><Environment preset="city"/></>}
export default function MedicationProductStory3D(){const section=useRef<HTMLElement>(null),progress=useRef(0),[reduced,setReduced]=useState(false);useEffect(()=>{const media=matchMedia("(prefers-reduced-motion: reduce)");setReduced(media.matches);if(media.matches)return;gsap.registerPlugin(ScrollTrigger);const ctx=gsap.context(()=>{gsap.to(progress,{current:1,ease:"none",scrollTrigger:{trigger:section.current,start:"top 75%",end:"bottom 25%",scrub:.6}});gsap.fromTo(`.${styles.storyStep}`,{opacity:.3,y:18},{opacity:1,y:0,stagger:.1,scrollTrigger:{trigger:section.current,start:"top 65%",end:"bottom 45%",scrub:true}})},section);return()=>ctx.revert()},[]);return <section ref={section} className={styles.storySection} aria-labelledby="product-story-title"><div className={styles.storyCanvas} aria-hidden="true">{reduced?<div className={styles.storyFallback}><span>e-Documentation</span><b>Consistency Engine</b><span>IPMOE</span></div>:<Canvas dpr={[1,1.5]} camera={{position:[0,1,8],fov:42}} gl={{antialias:true,alpha:true,powerPreference:"high-performance"}}><Scene progress={progress}/></Canvas>}</div><div className={styles.storyCopy}><p className={styles.eyebrow}>Read-only product flow</p><h2 id="product-story-title">Two applications. One consistency check. Human judgement at the end.</h2>{["Separate applications provide structured medication fields.","Data tokens flow one-way into the deterministic engine.","Aligned fields become MATCH; ambiguity remains REVIEW.","Mandatory conflicts become MISMATCH and enter the workflow rail.","n8n assigns, waits and escalates. It does not determine correctness.","The healthcare professional returns to the relevant source application when correction is required."].map((x,i)=><article className={styles.storyStep} key={x}><span>{String(i+1).padStart(2,"0")}</span><p>{x}</p></article>)}</div></section>}
