export type Route="ORAL"|"IV"|"SUBCUTANEOUS"|"IM"|"RECTAL"|"PER_VAGINAL";
export type Result="MATCH"|"REVIEW"|"MISMATCH"|"NOT_APPLICABLE";
export type SourceSystem="E_DOCUMENTATION"|"IPMOE";
export interface MedicationRecord{sourceSystem:SourceSystem;sourceRecordId:string;patientId:string;encounterId:string;medicationCode:string;medicationName:string;formulation?:string;doseValue?:number;doseUnit?:string;route?:Route|string;frequencyType?:"INTERVAL"|"DUE_IN"|"SCHEDULED"|"FREE_TEXT";intervalMinutes?:number;scheduledTime?:string;isIntravenousFluid:boolean;fluidName?:string;fluidVolumeMl?:number;infusionDurationMinutes?:number;infusionRateMlHour?:number;indication?:string;specialInstructions?:string;orderStatus:string;authorId:string;documentedAt:string;version:number}
export interface FieldComparison{field:string;eDocumentationValue:unknown;ipmoeValue:unknown;normalisedEDocumentation:unknown;normalisedIpmoe:unknown;result:Result;reasonCode:string;explanation:string;ruleId:string;ruleVersion:string;action:string}
export interface Comparison{overallResult:Exclude<Result,"NOT_APPLICABLE">;message:string;fields:FieldComparison[];engineVersion:string}
export const rules={identity:{id:"MED-IDENTITY",version:"0.1"},dose:{id:"MED-DOSE",version:"0.1"},unit:{id:"MED-UNIT",version:"0.1"},route:{id:"MED-ROUTE",version:"0.1"},frequency:{id:"MED-TIMING",version:"0.1"},status:{id:"MED-STATUS",version:"0.1"},fluid:{id:"IVF-DETAILS",version:"0.1"},version:{id:"SOURCE-VERSION",version:"0.1"}} as const;
export const routeNormalisation:Record<string,Route>={PO:"ORAL",ORAL:"ORAL",IV:"IV",SC:"SUBCUTANEOUS",SUBCUTANEOUS:"SUBCUTANEOUS",IM:"IM",INTRAMUSCULAR:"IM",PR:"RECTAL",RECTAL:"RECTAL",PV:"PER_VAGINAL","PER VAGINAL":"PER_VAGINAL",PER_VAGINAL:"PER_VAGINAL"};
export function normaliseRoute(v?:string){return v?routeNormalisation[v.trim().toUpperCase()]:undefined}
export function normaliseTiming(v:Pick<MedicationRecord,"frequencyType"|"intervalMinutes"|"scheduledTime">){if(v.frequencyType==="INTERVAL"||v.frequencyType==="DUE_IN")return v.intervalMinutes;if(v.frequencyType==="SCHEDULED")return v.scheduledTime;return undefined}
export function normaliseName(v?:string){return v?.toLowerCase().replace(/[^a-z0-9]/g,"").replace("acetaminophen","paracetamol")}
const message={MATCH:"No configured discrepancy detected. Continue required clinical verification.",REVIEW:"The records may describe the same intended treatment, but one or more fields cannot be verified automatically.",MISMATCH:"A mandatory difference was detected. Review both source applications and follow the approved local workflow."} as const;
function field(field:string,a:unknown,b:unknown,na:unknown,nb:unknown,rule:{id:string;version:string},critical=true,forcedReview=false):FieldComparison{let result:Result="MATCH",reasonCode="EQUIVALENT_AFTER_NORMALISATION",explanation="Values match after prototype normalisation.",action="Continue required professional verification.";if(forcedReview||(na==null||nb==null)){result="REVIEW";reasonCode="VALUE_UNAVAILABLE_OR_AMBIGUOUS";explanation="One value is missing or cannot be verified by an enabled prototype rule.";action="Review both source applications and request clarification if required."}else if(na!==nb){result=critical?"MISMATCH":"REVIEW";reasonCode="VALUES_DIFFER";explanation="The source values remain different after normalisation.";action="Review both source applications and follow the approved local workflow."}return{field,eDocumentationValue:a,ipmoeValue:b,normalisedEDocumentation:na,normalisedIpmoe:nb,result,reasonCode,explanation,ruleId:rule.id,ruleVersion:rule.version,action}}
export function compareMedication(a:MedicationRecord,b:MedicationRecord):Comparison{const f=[field("Patient",a.patientId,b.patientId,a.patientId,b.patientId,rules.identity),field("Encounter",a.encounterId,b.encounterId,a.encounterId,b.encounterId,rules.identity),field("Medication",a.medicationName,b.medicationName,normaliseName(a.medicationName),normaliseName(b.medicationName),rules.identity,true,b.medicationName.includes("Brand")),field("Dose",a.doseValue,b.doseValue,a.doseValue,b.doseValue,rules.dose),field("Dose unit",a.doseUnit,b.doseUnit,a.doseUnit?.toLowerCase(),b.doseUnit?.toLowerCase(),rules.unit),field("Route",a.route,b.route,normaliseRoute(a.route),normaliseRoute(b.route),rules.route),field("Timing / frequency",a.scheduledTime??a.intervalMinutes,b.scheduledTime??b.intervalMinutes,normaliseTiming(a),normaliseTiming(b),rules.frequency,true,a.frequencyType==="FREE_TEXT"||b.frequencyType==="FREE_TEXT"||a.frequencyType!==b.frequencyType),field("Status",a.orderStatus,b.orderStatus,a.orderStatus.toLowerCase(),b.orderStatus.toLowerCase(),rules.status),field("Source version",a.version,b.version,a.version,b.version,rules.version,false,a.version!==b.version)];if(a.isIntravenousFluid||b.isIntravenousFluid){f.push(field("IVF identity",a.fluidName,b.fluidName,normaliseName(a.fluidName),normaliseName(b.fluidName),rules.fluid),field("IVF volume",a.fluidVolumeMl,b.fluidVolumeMl,a.fluidVolumeMl,b.fluidVolumeMl,rules.fluid),field("IVF duration",a.infusionDurationMinutes,b.infusionDurationMinutes,a.infusionDurationMinutes,b.infusionDurationMinutes,rules.fluid,true,Boolean((a.infusionDurationMinutes&&!b.infusionDurationMinutes&&b.infusionRateMlHour)||(b.infusionDurationMinutes&&!a.infusionDurationMinutes&&a.infusionRateMlHour))));}const overallResult=f.some(x=>x.result==="MISMATCH")?"MISMATCH":f.some(x=>x.result==="REVIEW")?"REVIEW":"MATCH";return{overallResult,message:message[overallResult],fields:f,engineVersion:"MCV-0.1.0"}}
