import {compareMedication,type MedicationRecord,type Result} from "./medication-engine";
export interface DemoCase{id:string;title:string;kind:"MEDICATION"|"IVF";workflowStatus:"Unassigned"|"In review"|"Clarification requested"|"Closed";eDocumentation:MedicationRecord;ipmoe:MedicationRecord;comparison:ReturnType<typeof compareMedication>}
const names=["Paracetamol","Amoxicillin","Cefazolin","Enoxaparin","Medication A","Medication B","Medication C","Normal saline","Dextrose","Medication D"];
const route=["ORAL","ORAL","IV","SUBCUTANEOUS","IM","RECTAL","PER_VAGINAL","IV","IV","IV"];
const dose=[1,500,1,40,5,10,1,1000,500,250],unit=["g","mg","g","mg","unit","mg","unit","mL","mL","mg"],mins=[360,480,60,720,30,480,720,480,240,360];
function record(i:number,source:"E_DOCUMENTATION"|"IPMOE"):MedicationRecord{return{sourceSystem:source,sourceRecordId:`${source==="E_DOCUMENTATION"?"EDOC":"IPM"}-${String(i+1).padStart(3,"0")}`,patientId:`DEMO-P${String(i+1).padStart(3,"0")}`,encounterId:`DEMO-E${String(i+1).padStart(3,"0")}`,medicationCode:`DEMO-MED-${i+1}`,medicationName:names[i],doseValue:dose[i],doseUnit:unit[i],route:route[i],frequencyType:i===2||i===4?"DUE_IN":"INTERVAL",intervalMinutes:mins[i],isIntravenousFluid:i===7||i===8,fluidName:i===7||i===8?names[i]:undefined,fluidVolumeMl:i===7||i===8?dose[i]:undefined,infusionDurationMinutes:i===7?480:i===8?240:undefined,orderStatus:"Active",authorId:"DEMO-AUTHOR",documentedAt:"2026-07-12T09:00:00Z",version:1}}
function make(group:"M"|"P"|"X",i:number):DemoCase{const a=record(i,"E_DOCUMENTATION"),b=record(i,"IPMOE");if(group==="P"){if(i===0)b.route=undefined;if(i===1)b.medicationName="AmoxiBrand (fictional)";if(i===2){b.frequencyType="FREE_TEXT";b.intervalMinutes=undefined}if(i===3){b.frequencyType="SCHEDULED";b.scheduledTime="08:00 / 20:00"}if(i===4){b.frequencyType="FREE_TEXT";b.intervalMinutes=undefined;b.specialInstructions="give promptly"}if(i===5)b.specialInstructions=undefined;if(i===6)a.doseValue=undefined;if(i===7)a.infusionDurationMinutes=undefined;if(i===8){b.infusionDurationMinutes=undefined;b.infusionRateMlHour=125}if(i===9)b.version=2}if(group==="X"){if(i===0)b.doseValue=.5;if(i===1)b.route="IV";if(i===2)b.doseValue=2;if(i===3)b.route="IM";if(i===4)b.intervalMinutes=90;if(i===5)b.intervalMinutes=720;if(i===6)b.route="ORAL";if(i===7)b.fluidVolumeMl=500;if(i===8)b.infusionDurationMinutes=480;if(i===9)b.orderStatus="Discontinued"}const id=`CASE-${group}${String(i+1).padStart(2,"0")}`;const comparison=compareMedication(a,b);return{id,title:names[i],kind:a.isIntravenousFluid?"IVF":"MEDICATION",workflowStatus:group==="M"?"Closed":group==="P"?"In review":"Unassigned",eDocumentation:a,ipmoe:b,comparison}}
export const demoCases=[...Array.from({length:10},(_,i)=>make("M",i)),...Array.from({length:10},(_,i)=>make("P",i)),...Array.from({length:10},(_,i)=>make("X",i))];
// P06 models PRN metadata absent from the mock IPMOE extract. It is a non-critical review exception.
const prnCase=demoCases.find(c=>c.id==="CASE-P06");
if(prnCase){prnCase.eDocumentation.specialInstructions="PRN";prnCase.comparison.overallResult="REVIEW";prnCase.comparison.message="The records may describe the same intended treatment, but one or more fields cannot be verified automatically.";prnCase.comparison.fields.push({field:"Special instructions",eDocumentationValue:"PRN",ipmoeValue:undefined,normalisedEDocumentation:"prn",normalisedIpmoe:undefined,result:"REVIEW",reasonCode:"VALUE_UNAVAILABLE_OR_AMBIGUOUS",explanation:"PRN status is absent from the mock IPMOE extract.",ruleId:"MED-TIMING",ruleVersion:"0.1",action:"Review both source applications and request clarification if required."})}
export const caseCounts=demoCases.reduce((a,c)=>({...a,[c.comparison.overallResult]:a[c.comparison.overallResult]+1}),{MATCH:0,REVIEW:0,MISMATCH:0} as Record<Exclude<Result,"NOT_APPLICABLE">,number>);
if(demoCases.length!==30||caseCounts.MATCH!==10||caseCounts.REVIEW!==10||caseCounts.MISMATCH!==10)throw new Error("Synthetic case invariant failed");
